{% set name = "mypy-protobuf" %}
{% set version = "3.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 912fb281f7c7b3e3a7c9b8695712618a716fddbab70f6ad63eaf68eda80c5efe

build:
  number: 0
  noarch: python
  entry_points:
    - protoc-gen-mypy = mypy_protobuf.main:main
    - protoc-gen-mypy_grpc = mypy_protobuf.main:grpc
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - protobuf >=4.23.4
    - types-protobuf >=3.19.5

test:
  imports:
    - mypy_protobuf
    - mypy_protobuf.extensions_pb2
  commands:
    - cat /dev/null | protoc-gen-mypy
    - cat /dev/null | protoc-gen-mypy_grpc
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dropbox/mypy-protobuf
  summary: Generate mypy stub files from protobuf specs
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
    - asford
