{% set name = "mypy-protobuf" %}
{% set version = "3.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mypy-protobuf-{{ version }}.tar.gz
  sha256: 7d75a079651b105076776a35a5405e3fa773b8a167118f1b712e443e9a6c18a2

build:
  number: 0
  noarch: python
  entry_points:
    - protoc-gen-mypy = mypy_protobuf.main:main
    - protoc-gen-mypy_grpc = mypy_protobuf.main:grpc
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - protobuf >=3.19.3
    - types-protobuf >=3.19.5

test:
  imports:
    - mypy_protobuf
    - mypy_protobuf.extensions_pb2
  commands:
    - cat /dev/null | protoc-gen-mypy
    - cat /dev/null | protoc-gen-mypy_grpc
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dropbox/mypy-protobuf
  summary: Generate mypy stub files from protobuf specs
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
    - asford
